### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by GCuser99** [Bill-Stewart/UninsIS#1]
Hope you don't mine me making a feature request here in issues...

I found your DLL very useful - thank you for sharing!

My usage case is different than the ones that you refer to in your readme file. I have an ActiveX DLL that I want to distribute/register using Inno Setup. I want to allow the user to (re)install the DLL in a location of their choice (DisableDirPage=no). If the user had already installed an older (or even same or newer) version as the one they are currently installing, and they decide to change the install location, then I wanted to first uninstall the previously installed version from the old location, so that there is only one version on the system at any one point in time. Your DLL works perfect for that objective. Here is my script:
```pascal
function PrepareToInstall(var NeedsRestart: Boolean): string;

var oldInstallDir: String; newInstallDir: String;
var isDifferentLocation : Boolean;
var isDifferentVersion : Boolean;
var isInstalled: Boolean;
var alwaysUninstall: Boolean;

begin
  // set alwaysUninstall to true if uninstall
  // should run regardless of version and location compare
  alwaysUninstall := false;
  isDifferentLocation := false;
  isDifferentVersion := false;

  oldInstallDir := WizardForm.PrevAppDir;
  newInstallDir := ExpandConstant('{app}');
  
  if oldInstallDir <> newInstallDir then isDifferentLocation := true;

  if CompareISPackageVersion() <> 0  then isDifferentVersion := true;

  isInstalled := IsISPackageInstalled()

  if isInstalled then
    begin
      if isDifferentLocation or isDifferentVersion or alwaysUninstall then
        UninstallISPackage();
    end;

  result := '';
end;
```

The above seems to be working for me so far. Anyway, I wanted to give you that feedback and also see what you think about adding a new DLL function named like DLLIsInstallLocationDifferentThanPrevious that does the same as these lines:
```pascal
  oldInstallDir := WizardForm.PrevAppDir;
  newInstallDir := ExpandConstant('{app}');
  isDifferentLocation := false;
  if oldInstallDir <> newInstallDir then isDifferentLocation := true;
```

Thanks!

**Comment by Bill-Stewart** [comment]
Hi, thanks for the feature request. However, I want to restrict functionality in the DLL only to things you _can't_ do (or can't do easily) from Inno Setup. Since it sounds like you have a solution that's working for you, I don't see a compelling reason to update the DLL.
