### ISSUE TITLE
Feature request: more than 4 version segments

### ISSUE THREAD

**Issue by paynesworld** [Bill-Stewart/UninsIS#2]
Hi there, great tool!  I'm looking forward to using it in my project.

I'm running into an issue that I'm hoping you can consider though.  In our solution we append the name of the git branch to the end of the version string, so that we can keep track of the branch that generated the installer.  So our version strings look something like this:

2.2.0.1.MarchReleaseCandidate

We only include this extra portion when we build from a working branch.  For version-comparison purposes these branch-name elements can be ignored since the version info is all that matters for us (we don't repeat version #'s across branches, etc).

It looks like this use case could be easily supported with a pretty minor change to wsISPackage.pp, GetVersionArray() line 136 to skip checking for versions with more than 4 segments.  I'd fork the code and compile my own version with this change but not a Pascal user and I'm having trouble getting a compiler to generate a DLL.

Any chance you would consider making a change in your main branch to support this case?  Thanks very much.

**Comment by Bill-Stewart** [comment]
I don't anticipate supporting this because UninsIS.dll reads the version number information, not the version number string, which is a separate entity. For more information, see here:

[What can I do if I don't want my file version number to be a sequence of four integers?](https://devblogs.microsoft.com/oldnewthing/20230503-51/?p=108135)

**Comment by paynesworld** [comment]
Thanks for the quick response!

In our case we're deploying a .NET solution.  The application files have a "file version" and an "informational version".  We set the "file version" to the 4-segment build number, and the "informational version" to the (in our case) 5-segment version that includes the branch name.  In our Inno Setup installer we configure the AppVersion to show the "informational version" so that it shows up in the Add/Remove Programs dialog in Windows.  The article you linked is related more to the "file version" I think -- which is not necessarily tied to the AppVersion to display in Inno Setup.  Maybe there's another property to set in my Inno Setup project to get the 5-segment version to show up like I want in Add/Remove Programs while still setting the 4-segment version in the DisplayVersion field in the registry?  I'll do some research on that.

I'm happy to roll my own custom version of your tool to support my specific needs -- would you be willing to provide a pointer to how to compile the project with my local changes?  I downloaded FreePascal but I fully admit my lack of knowledge of compiling Pascal projects.  Perhaps there's a better compiler to use?

Thanks again...

**Comment by Bill-Stewart** [comment]
If I understand your request, you're saying your scenario would be supported if the DLL "ignored" version parts greater than 4, is that correct? If so, that's an interesting idea to consider, but I'll have to think about the potential impact of the change, because it means that the version number string check will accept non-standard version number strings.

Regarding compiling: All that's needed is the latest version of the Free Pascal (FPC) compiler.

**Comment by paynesworld** [comment]
For my specific use case, yes -- ignoring the version parts after 4 would work.  I agree though that might not be a good generic implementation.

As we've been discussing though, I've discovered that I can set the AppVerName property in my Inno Setup project and get the effect I want, where I display the 5-segment version info as part of the application name.  This shows up in the setup dialogs and in the add/remove programs dialog, which is exactly what I want.  I can then set the AppVersion to the 4-segment version and your code should work as-is.  So I think I'm good to go with that approach!

So many version fields floating around...

Thanks again for your consideration -- I'm excited to use this tool to support my need to update an existing 32-bit application to 64-bit, and uninstall the 32-bit version as part of the upgrade.  Looks like it will work beautifully!

**Comment by Bill-Stewart** [comment]
Sounds good!
